name: CUDA CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  checks-cuda:
    uses: ./.github/workflows/devcontainer-checks.yml
    with:
      runs-on: '["self-hosted", "cuda-gpu"]'
      devcontainer-config: .devcontainer/cuda/devcontainer.json
      image-name: devcontainer-cuda
      cleanup-stale-container: true
      build-run-cmd: |
        show-platform
        python3 -c "import torch; assert torch.cuda.is_available(), 'CUDA not available'"
